#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo "🛡️ Final security check before push..."

# Используем run-p для параллельного запуска.
# Если любая из команд упадет, push будет отменен.
npx run-p type-check test